name: Playwright Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Maven
        uses: s4u/setup-maven-action@v1.7.0
        with:
          checkout-fetch-depth: 0
          java-version: 17
          java-distribution: temurin
          maven-version: 3.9.9

      - name: Build project
        run: mvn -B install -DskipTests --no-transfer-progress

      - name: Install Playwright browsers and dependencies
        run: mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install --with-deps"

      - name: Run Playwright Tests
        run: mvn verify

      - name: Archive trace files
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: traces
          path: target/traces/*.zip

      - name: Deploy Allure Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/site/allure-maven-plugin